# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce0b0b9a531d5020b4711395c4600b966f425dea2fc795b4d9859279e49c4d5b744ec67186d9e4820419ee47dcf32c7c03c42c252474344bb856db8b16eea5bf

test:
  secret_key_base: 406df3c392eabc52ab41156abb2f90927ce355bff6dd4eea49dcf4d2bee33ecad3c25142ca478eac561491900e155fd5f04616de8e14772184facf9ecdd319a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
